baseURL = "https://hide0123.github.io/home/"
title = "BamTech"
theme = "docsy"

enableRobotsTXT = true

# language settings
contentDir = "content/ja"
defaultContentLanguage = "ja"
# tell Hugo not to include the /ja/ element in the URL path for Japanese docs
defaultContentLanguageInSubdir = false
# useful when translating
enableMissingTranslationPlaceholders = true

[services]
  [services.googleAnalytics]
    id = "G-W1M3E9YDR6"

[menu]
  [[menu.main]]
    name = "Documentation"
    weight = -101
    pre = "<i class='fas fa-book pr-2'></i>"
    url = "/docs/"
  [[menu.main]]
    name = "Blog"
    weight = -100
    pre = "<i class='fas fa-rss pr-2'></i>"
    url = "/blog/"
  [[menu.main]]
    name = "GitHub"
    weight = -99
    pre = "<i class='fab fa-github pr-2'></i>"
    url = "https://github.com/hide0123/home"

[languages]
  [languages.ja]
    title = "BamTech"
    description = "Welcome to my website!"
    languageName = "日本語"

[params]
  copyright = "BamTech"
  images = "img/ogp.png"

[params.links]
  [[params.links.user]]
    name = "Twitter"
    url = "https://twitter.com/bam_b0o_"
    icon = "fab fa-twitter"
  [[params.links.user]]
    name = "Github"
    url = "https://github.com/hide0123"
    icon = "fab fa-github"